[package]
name = "periodically"
version = "0.1.0"
edition = "2021"
authors = ["David Collard <davidcollardprofessional@gmail.com"]
license-file = "LICENSE.txt"
keywords = ["periodic", "cron", "job"]
categories = ["concurrency"]

[dependencies]
